@extends('layouts.dashboardlayout')
@section('title', 'Dealer Performance Dashboard')
@section('breadcrumb1', 'Performance Management')
@section('breadcrumb', 'Dealer Performance')
@section('pageTitle', 'Dealer Performance Dashboard')
@section('content')

<div class="container-fluid">

    <!-- Dashboard Header -->
    <div class="row">
        <div class="col-md-12">
            <h3 class="mb-4">Dealer Performance Overview</h3>
        </div>
    </div>


    <form action="{{ route('sales.filter') }}" method="GET">
        @csrf
        <div class="row gy-2 gx-2 align-items-center">
            @if (Auth::user()->role_id === 5)
            <div class="col-auto">
                <div class="mb-2">
                    <label for="showroom_id" class="form-label">Dealer</label>
                    <select id="showroom_id" name="showroom_id" class="form-select">
                        <option value="" selected>Select...</option>
                        @foreach ($showrooms as $showroom)
                        <option value="{{ $showroom->id }}">{{ $showroom->shr_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-auto">
                <div class="mb-0">
                    <label for="showroom_id" class="form-label"></label>
                    <button type="submit" class="mb-2 btn btn-primary form-select">Apply Filter</button>
                </div>
            </div>
            @endif
        </div>
    </form>


    <!-- Summary Cards -->
    <div class="row mt-3">
        <!-- Total Sales Card -->
        <div class="mb-3 col-md-3">
            <div class="text-white card bg-primary" style="height:100%;">
                <div class="text-black card-header">Total Services</div>
                <div class="card-body">
                    <h4 class="card-title">{{ $total_services }}</h4>
                    <p class="card-text">Total services count generated by the dealer.</p>
                </div>
            </div>
        </div>
        <!-- Sales Volume Card -->
        <div class="mb-3 col-md-3">
            <div class="text-white card bg-success" style="height:100%;">
                <div class="text-black card-header">Total services Cost</div>
                <div class="card-body">
                    <h4 class="card-title">{{ $total_services_cost }}$</h4>
                    <p class="card-text">Total services cost generated by the dealer</p>
                </div>
            </div>
        </div>
        <!-- Average Order Value Card -->
        <div class="mb-3 col-md-3">
            <div class="text-white card bg-warning" style="height:100%;">
                <div class="text-black card-header">Total Vehicles</div>
                <div class="card-body">
                    <h4 class="card-title">{{ $total_vehicles }}</h4>
                    <p class="card-text">Total Vehicles of the dealers.</p>
                </div>
            </div>
        </div>
        <!-- Sales Growth Card -->
        <div class="mb-3 col-md-3">
            <div class="text-white card bg-danger" style="height:100%;">
                <div class="text-black card-header">Damaged Vehicle</div>
                <div class="card-body">
                    <h4 class="card-title">{{ $total_accidents }}</h4>
                    <p class="card-text">Damaged Vehicle of the dealers.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Graphs Row -->
    <div class="row">
        <!-- Sales Performance Graph -->
        <div class="col-md-6">
            <div class="mb-4 card">
                <div class="card-header">
                    Sales Performance
                </div>
                <div class="card-body">
                    <canvas id="salesPerformanceChart"></canvas>
                </div>
            </div>
        </div>
        <!-- Return Rate & Outstanding Payments -->
        <div class="col-md-6">
            <div class="mb-4 card">
                <div class="card-header">
                    Return Rate & Outstanding Payments
                </div>
                <div class="card-body">
                    <canvas id="returnRateOutstandingPaymentsChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Detailed Data Table -->
    <div class="row">
        <div class="col-md-12">
            <div class="mb-4 card">
                <div class="card-header">
                    Dealer Detailed Performance Data
                </div>
                <div class="card-body">
                    <table id="performanceTable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Metric</th>
                                <th>Value</th>
                                <th>Target</th>
                                <th>Performance</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Total Sales</td>
                                <td>$100,000</td>
                                <td>$120,000</td>
                                <td><span class="badge bg-danger">Below Target</span></td>
                            </tr>
                            <tr>
                                <td>Sales Volume</td>
                                <td>200 units</td>
                                <td>250 units</td>
                                <td><span class="badge bg-warning">Near Target</span></td>
                            </tr>
                            <tr>
                                <td>Average Order Value</td>
                                <td>$500</td>
                                <td>$550</td>
                                <td><span class="badge bg-info">On Track</span></td>
                            </tr>
                            <tr>
                                <td>Sales Growth</td>
                                <td>15%</td>
                                <td>20%</td>
                                <td><span class="badge bg-warning">Below Target</span></td>
                            </tr>
                            <tr>
                                <td>Return Rate</td>
                                <td>2%</td>
                                <td>1%</td>
                                <td><span class="badge bg-success">Good</span></td>
                            </tr>
                            <tr>
                                <td>Outstanding Payments</td>
                                <td>$10,000</td>
                                <td>$5,000</td>
                                <td><span class="badge bg-danger">High</span></td>
                            </tr>
                            <tr>
                                <td>Credit Limit</td>
                                <td>$50,000</td>
                                <td>$60,000</td>
                                <td><span class="badge bg-info">On Track</span></td>
                            </tr>
                            <tr>
                                <td>Last Order Date</td>
                                <td>2024-08-30</td>
                                <td>—</td>
                                <td><span class="badge bg-info">Recent</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $.ajax({
            url: "{{ route('monthly_service_cost') }}",
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                createChart(data);
                console.log(data)
            }
        });


        function createChart(data) {
            // document.addEventListener("DOMContentLoaded", function() {
            // Sales Performance Chart
            var salesCtx = document.getElementById('salesPerformanceChart').getContext('2d');
            var salesPerformanceChart = new Chart(salesCtx, {
                type: 'line',
                data: {
                    labels: data.labels,
                    datasets: [{
                        label: 'Total Sales',
                        data: data.monthly_cost,
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 2,
                        fill: true
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        }

        // Return Rate & Outstanding Payments Chart
        var returnRateCtx = document.getElementById('returnRateOutstandingPaymentsChart').getContext('2d');
        var returnRateOutstandingPaymentsChart = new Chart(returnRateCtx, {
            type: 'bar',
            data: {
                labels: ['Return Rate', 'Outstanding Payments'],
                datasets: [{
                    label: 'Percentage',
                    data: [2, 10],
                    backgroundColor: [
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)'
                    ],
                    borderWidth: 2
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        // DataTable for Detailed Performance Data
        $('#performanceTable').DataTable({
            paging: true,
            searching: true,
            ordering: true,
            lengthChange: false,
            pageLength: 10,
            info: true,
            language: {
                searchPlaceholder: "Search records...",
                paginate: {
                    previous: "Prev",
                    next: "Next"
                },
                info: "Showing _START_ to _END_ of _TOTAL_ entries",
                infoEmpty: "No entries found",
                infoFiltered: "(filtered from _MAX_ total entries)"
            }
        });
    });
</script>

@endpush